### ISSUE TITLE
ToDo: Checklist - Änderung Settings

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#39]
- [ ] Settings --> Einbau Video zeigen an/aus
- [ ] Seetings --> Einbau Video erlauben einzusenden ja/nein
- [ ] Settings --> Einbau Affiliate ein/aus
- [ ] Seetings --> Einbau Affiliate Amazon ein/aus

**Comment by DavidGuetl** [comment]
Hab einige Einstellungen entfernt -> Bitte auf meiner Seite davor nachsehen -> Ebenso ein paar Fehler korregiert.

**Comment by Catzenjaeger** [comment]
ja aber diese 4 Sachen oben müssen noch rein. Heisst im file infusions.php muss das rein und auch in die datei admin_figurelib_settings

**Comment by Catzenjaeger** [comment]
eingebaut ist ... die if abfragen mussen noch gesetzt werden. da kein fehler im dem sinnen mache ihc das mal zu
