### ISSUE TITLE
ToDo: Checklist Onlinerecht/Bestimmungen

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#40]
- [ ] Impressum --> https://de.wikipedia.org/wiki/Impressumspflicht
- [ ] Cookies?
- [ ] Datenschutzbelehrung --> https://de.wikipedia.org/wiki/Datenschutzerkl%C3%A4rung
- [ ] Bildrechte 
- [ ] Videorechte
- [ ] Affiliates Links Kennzeichen im Context 
- [ ] Klare Abtrennung von Werbung und Content
